language: node_js

cache:
  apt: true
  directories:
    - node_modules

node_js:
  - 8

install:
  - npm install hexo-cli -g
  - npm install coveralls

script:
  - hexo clean
  - hexo generate
  - cd public
  - git init
  - git add .
  - git commit -m "Update docs"
  - git push --quiet --force "https://${GITHUB_TOKEN}@github.com/flc1125/hexo-blog.git" master:gh-pages

branches:
  only:
    - master