# 头部菜单，title: link
menu:
  Github: https://github.com/flc1125

# 是否显示目录
TOC: false

# 是否自动播放音乐
autoplay: false

# 默认音乐
mp3: ''

# 首页封面图, 为空时取文章的cover作为封面
welcome_cover: # /img/welcome-cover.jpg

# 默认文章封面图
cover: /covers/default-cover.jpg

# 是否关闭默认滚动条
scrollbar: true

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否自动展开评论框
    autoExpand: true
    # 应用编号
    clientID: 'a6ab008c11203b8ab049'
    # 应用秘钥
    clientSecret: '6103f135e5a916e3d0c2b8cb9dfd943b07cb8208'
    # issue仓库名
    repo: 'hexo-blog'
    # Github名
    owner: 'flc1125'
    # Github名
    admin: ['flc1125']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords: Fechin

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics:

# 网站ico
favicon: /images/logo.png

# rss文件
rss: atom.xml
